import { useState, useEffect } from 'react'
import { CheckCircle, XCircle, Loader, RefreshCw, Eye, EyeOff } from 'lucide-react'
import api from '../api/client'

function Section({ title, children }) {
  return (
    <div className="bg-surface border border-border rounded-lg p-5 space-y-4">
      <h2 className="text-text-primary font-semibold text-sm border-b border-border pb-2">{title}</h2>
      {children}
    </div>
  )
}

function Field({ label, children }) {
  return (
    <div>
      <label className="block text-text-muted text-xs mb-1">{label}</label>
      {children}
    </div>
  )
}

const inputClass = 'w-full bg-bg border border-border rounded-md px-3 py-2 text-text-primary text-sm focus:outline-none focus:border-primary'

export default function Settings() {
  const [settings, setSettings] = useState({})
  const [poolStats, setPoolStats] = useState([])
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [saved, setSaved] = useState(false)
  const [dsKey, setDsKey] = useState('')
  const [showKey, setShowKey] = useState(false)
  const [dsTest, setDsTest] = useState(null)
  const [dsTesting, setDsTesting] = useState(false)
  const [poolLoading, setPoolLoading] = useState(false)

  const load = async () => {
    try {
      const [s, p] = await Promise.all([
        api.get('/settings'),
        api.get('/settings/content-pool').catch(() => ({ data: [] })),
      ])
      setSettings(s.data)
      setPoolStats(p.data)
    } catch {}
    setLoading(false)
  }

  useEffect(() => {
    load()
    const id = setInterval(() => {
      api.get('/settings/content-pool').then(r => setPoolStats(r.data)).catch(() => {})
    }, 30000)
    return () => clearInterval(id)
  }, [])

  const set = (k, v) => setSettings(s => ({ ...s, [k]: v }))

  const save = async () => {
    setSaving(true)
    try {
      const payload = { ...settings }
      if (dsKey) payload.deepseek_api_key = dsKey
      delete payload.deepseek_api_key_display
      await api.put('/settings', payload)
      setSaved(true)
      setTimeout(() => setSaved(false), 3000)
    } catch {}
    setSaving(false)
  }

  const testDeepSeek = async () => {
    if (!dsKey && settings.deepseek_api_key !== '***SET***') return
    setDsTesting(true)
    setDsTest(null)
    try {
      const res = await api.post('/settings/test-deepseek', { api_key: dsKey || 'use_stored' })
      setDsTest(res.data)
    } catch (e) {
      setDsTest({ success: false, error: e.response?.data?.detail || 'Test failed', latency_ms: 0, model: '' })
    }
    setDsTesting(false)
  }

  const resetPool = async (mailboxId, email) => {
    if (!confirm(`Reset content pool for ${email}? All used content records will be deleted.`)) return
    setPoolLoading(true)
    try {
      await api.delete(`/settings/content-pool/${mailboxId}`)
      await load()
    } catch {}
    setPoolLoading(false)
  }

  if (loading) return <div className="text-text-muted text-sm">Loading...</div>

  return (
    <div className="space-y-5 max-w-3xl">
      <h1 className="text-text-primary font-bold text-xl">Settings</h1>

      <Section title="Content Engine">
        <Field label="Content Mode">
          <div className="flex gap-2">
            {[['templates', 'Static Templates'], ['deepseek', 'DeepSeek AI']].map(([val, lbl]) => (
              <button key={val} onClick={() => set('content_mode', val)}
                className={`flex-1 py-2 text-sm rounded-md border transition-colors ${settings.content_mode === val ? 'border-primary bg-primary/10 text-primary' : 'border-border text-text-muted hover:border-primary/50'}`}>
                {lbl}
              </button>
            ))}
          </div>
        </Field>

        {settings.content_mode === 'deepseek' ? (
          <div className="space-y-3">
            <div className="bg-primary/5 border border-primary/20 rounded-md p-3 text-xs text-text-muted">
              When enabled, every warmup email is uniquely generated by DeepSeek AI. Falls back to static templates automatically if the API is unavailable.
            </div>
            <Field label="DeepSeek API Key">
              <div className="flex gap-2">
                <div className="relative flex-1">
                  <input type={showKey ? 'text' : 'password'} value={dsKey}
                    onChange={(e) => setDsKey(e.target.value)}
                    placeholder={settings.deepseek_api_key === '***SET***' ? '••• Key is set — enter new key to replace •••' : 'sk-...'}
                    className={`${inputClass} pr-9`} />
                  <button onClick={() => setShowKey(!showKey)} className="absolute right-2 top-2 text-text-muted hover:text-text-primary">
                    {showKey ? <EyeOff size={14} /> : <Eye size={14} />}
                  </button>
                </div>
                <button onClick={testDeepSeek} disabled={dsTesting || (!dsKey && settings.deepseek_api_key !== '***SET***')}
                  className="border border-border hover:border-primary text-text-primary text-sm px-3 py-2 rounded-md disabled:opacity-40 transition-colors flex items-center gap-2">
                  {dsTesting ? <Loader size={14} className="animate-spin" /> : 'Test'}
                </button>
              </div>
              {dsTest && (
                <p className={`flex items-center gap-1 text-xs mt-1 ${dsTest.success ? 'text-success' : 'text-danger'}`}>
                  {dsTest.success ? <CheckCircle size={12} /> : <XCircle size={12} />}
                  {dsTest.success ? `Connected (${dsTest.latency_ms}ms)` : dsTest.error}
                </p>
              )}
            </Field>
            <Field label="Max Retries on API Failure">
              <input type="number" min={1} max={10} value={settings.deepseek_max_retries || '3'} onChange={(e) => set('deepseek_max_retries', e.target.value)} className={inputClass} />
            </Field>
          </div>
        ) : (
          <div className="bg-white/5 border border-border rounded-md p-3 text-xs text-text-muted">
            Uses a built-in library of 60 subjects and 100 body templates. Content is rotated and deduplicated automatically. The pool resets when 80% exhaustion is reached.
          </div>
        )}

        <div>
          <div className="flex items-center justify-between mb-2">
            <p className="text-text-muted text-xs font-medium uppercase tracking-wide">Content Pool Status</p>
            <button onClick={load} className="text-text-muted hover:text-text-primary">
              <RefreshCw size={12} className={poolLoading ? 'animate-spin' : ''} />
            </button>
          </div>
          {poolStats.length === 0 ? (
            <p className="text-text-muted text-xs">No sender mailboxes yet</p>
          ) : (
            <div className="bg-bg border border-border rounded-md overflow-hidden">
              <table className="w-full text-xs">
                <thead>
                  <tr className="border-b border-border">
                    {['Mailbox', 'Pool Used', 'Source', 'Actions'].map(h => (
                      <th key={h} className="px-3 py-2 text-left text-text-muted font-medium">{h}</th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {poolStats.map((s) => (
                    <tr key={s.mailbox_id} className="border-b border-border last:border-0">
                      <td className="px-3 py-2 font-mono text-text-primary truncate max-w-xs">{s.mailbox_email}</td>
                      <td className="px-3 py-2">
                        <div className="flex items-center gap-2">
                          <div className="h-1.5 w-20 bg-border rounded-full overflow-hidden">
                            <div className="h-full bg-primary rounded-full" style={{ width: `${s.pool_exhaustion_percent || 0}%` }} />
                          </div>
                          <span className="text-text-muted font-mono">{(s.pool_exhaustion_percent || 0).toFixed(1)}%</span>
                        </div>
                      </td>
                      <td className="px-3 py-2">
                        <span className={`px-1.5 py-0.5 rounded border text-xs ${settings.content_mode === 'deepseek' ? 'text-primary border-primary/30 bg-primary/10' : 'text-text-muted border-border'}`}>
                          {settings.content_mode === 'deepseek' ? 'AI' : 'Templates'}
                        </span>
                      </td>
                      <td className="px-3 py-2">
                        <button onClick={() => resetPool(s.mailbox_id, s.mailbox_email)}
                          className="text-text-muted hover:text-danger text-xs transition-colors">Reset</button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      </Section>

      <Section title="Warmup Schedule">
        <div className="grid grid-cols-2 gap-4">
          <Field label="Send Window Start Hour (0-23)">
            <select value={settings.send_hour_start || '7'} onChange={(e) => set('send_hour_start', e.target.value)} className={inputClass}>
              {Array.from({ length: 24 }, (_, i) => <option key={i} value={i}>{i}:00</option>)}
            </select>
          </Field>
          <Field label="Send Window End Hour (0-23)">
            <select value={settings.send_hour_end || '11'} onChange={(e) => set('send_hour_end', e.target.value)} className={inputClass}>
              {Array.from({ length: 24 }, (_, i) => <option key={i} value={i}>{i}:00</option>)}
            </select>
          </Field>
          <Field label="Min Delay Between Sends (seconds)">
            <input type="number" value={settings.min_delay_between_sends_seconds || '60'} onChange={(e) => set('min_delay_between_sends_seconds', e.target.value)} className={inputClass} />
          </Field>
          <Field label="Max Delay Between Sends (seconds)">
            <input type="number" value={settings.max_delay_between_sends_seconds || '300'} onChange={(e) => set('max_delay_between_sends_seconds', e.target.value)} className={inputClass} />
          </Field>
        </div>
      </Section>

      <Section title="Volume Settings">
        <div className="grid grid-cols-2 gap-4">
          <Field label="Weekly Volume Increase Per Mailbox">
            <input type="number" value={settings.weekly_volume_increase || '5'} onChange={(e) => set('weekly_volume_increase', e.target.value)} className={inputClass} />
          </Field>
          <Field label="Maximum Daily Volume Cap">
            <input type="number" value={settings.max_daily_volume || '50'} onChange={(e) => set('max_daily_volume', e.target.value)} className={inputClass} />
          </Field>
        </div>
      </Section>

      <Section title="IMAP Polling">
        <div className="grid grid-cols-2 gap-4">
          <Field label="Poll Interval (minutes)">
            <input type="number" value={settings.imap_poll_interval_minutes || '120'} onChange={(e) => set('imap_poll_interval_minutes', e.target.value)} className={inputClass} />
          </Field>
          <Field label="Seeds Per Send">
            <div className="grid grid-cols-2 gap-2">
              <input type="number" placeholder="Min" value={settings.min_seeds_per_send || '5'} onChange={(e) => set('min_seeds_per_send', e.target.value)} className={inputClass} />
              <input type="number" placeholder="Max" value={settings.max_seeds_per_send || '8'} onChange={(e) => set('max_seeds_per_send', e.target.value)} className={inputClass} />
            </div>
          </Field>
        </div>
      </Section>

      <Section title="Health Monitoring">
        <div className="grid grid-cols-2 gap-4">
          <Field label="Health Check Interval (hours)">
            <input type="number" value={settings.health_check_interval_hours || '24'} onChange={(e) => set('health_check_interval_hours', e.target.value)} className={inputClass} />
          </Field>
          <Field label="Auto-Pause Health Threshold (0-100)">
            <input type="number" min={0} max={100} value={settings.auto_pause_health_threshold || '50'} onChange={(e) => set('auto_pause_health_threshold', e.target.value)} className={inputClass} />
          </Field>
        </div>
      </Section>

      <div className="flex items-center gap-3">
        <button onClick={save} disabled={saving}
          className="bg-primary hover:bg-primary/80 disabled:opacity-50 text-white px-6 py-2.5 rounded-md text-sm font-medium transition-colors flex items-center gap-2">
          {saving ? <><Loader size={14} className="animate-spin" /> Saving...</> : 'Save Settings'}
        </button>
        {saved && (
          <span className="flex items-center gap-1 text-success text-sm">
            <CheckCircle size={14} /> Saved
          </span>
        )}
      </div>
    </div>
  )
}
